export type AITemplateName = 'minimal_luxury'|'dark_futuristic'|'soft_beauty'|'viral_tiktok'|'organic_nature'|'bold_sales';

export const themeTokens: Record<AITemplateName, Record<string,string>> = {
  minimal_luxury: {
    bg:'bg-white',textMain:'text-zinc-900',textSec:'text-zinc-500',font:'font-serif',
    promo:'bg-zinc-900 text-white tracking-widest font-light',header:'bg-white/90 border-b border-zinc-100',
    brand:'text-zinc-900 tracking-[0.2em] font-serif uppercase',
    btnSecondary:'bg-transparent border border-zinc-900 hover:bg-zinc-900 hover:text-white text-zinc-900 font-normal rounded-none px-8 py-3',
    btnPrimary:'bg-zinc-900 hover:bg-black text-white font-normal rounded-none px-12 py-5 shadow-2xl',
    heroBg:'bg-zinc-50/50',accentBg:'bg-white border border-zinc-200 text-zinc-900',accentText:'text-zinc-400 font-serif italic',heroBlob:'hidden',
    sectionDark:'bg-zinc-900 text-white',sectionDarkAccent:'from-zinc-950 to-zinc-900 border-zinc-800',sectionWhite:'bg-white',sectionLight:'bg-zinc-50',
    card:'bg-white border border-zinc-200 hover:border-zinc-400 rounded-none',checkoutBg:'bg-zinc-50',
    checkoutCard:'border-0 shadow-2xl rounded-none',checkoutDark:'bg-zinc-900 text-white',
    heroImg:'rounded-none shadow-2xl border-4 border-zinc-100',trustBadge:'bg-white border border-zinc-100 text-zinc-900 shadow-xl rounded-none',
    trustIcon:'bg-zinc-100 text-zinc-900 rounded-none',trustText:'text-zinc-500',
    featCard:'rounded-none',featIcon:'bg-zinc-100 text-zinc-900 rounded-none',
    reviewCard:'rounded-none',reviewText:'text-zinc-600',reviewAvatar:'bg-zinc-900 text-white rounded-none',
    inputStyle:'border-zinc-200 bg-white text-zinc-900 focus:border-zinc-900 rounded-none',
    footer:'bg-white text-zinc-500 border-t border-zinc-100',
  },
  dark_futuristic: {
    bg:'bg-[#030014]',textMain:'text-white',textSec:'text-indigo-200',font:'font-mono',
    promo:'bg-[#0a0f2c] border-b border-cyan-500/30 text-cyan-400 font-mono text-xs tracking-widest uppercase',
    header:'bg-[#030014]/50 border-b border-white/5 backdrop-blur-xl',
    brand:'text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-indigo-500 font-mono uppercase tracking-widest',
    btnSecondary:'hover:bg-white/5 text-cyan-400 font-mono text-sm border border-cyan-500/30 rounded-md px-6 py-2',
    btnPrimary:'bg-indigo-600 hover:bg-indigo-500 text-white font-mono rounded-md px-10 py-4 shadow-[0_0_30px_rgba(99,102,241,0.5)] border border-indigo-400/50',
    heroBg:'bg-[#030014]',accentBg:'bg-indigo-900/30 text-cyan-400 border border-indigo-500/30 font-mono text-xs rounded-full',
    accentText:'text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-indigo-400',
    heroBlob:'bg-gradient-to-tr from-cyan-500/20 to-indigo-600/20 opacity-30 filter blur-[100px]',
    sectionDark:'bg-[#050B14] border-y border-white/5',sectionDarkAccent:'from-[#0A0F2C] to-[#030014] border-indigo-500/20',
    sectionWhite:'bg-[#030014] border-y border-white/5',sectionLight:'bg-[#0a0f2c] border-y border-indigo-500/10',
    card:'bg-[#0a0f2c]/50 border border-white/5 hover:border-cyan-500/30 rounded-xl',checkoutBg:'bg-[#030014]',
    checkoutCard:'border border-indigo-500/20 bg-[#0a0f2c]/80 shadow-[0_0_40px_rgba(99,102,241,0.15)] rounded-2xl',checkoutDark:'bg-[#050B14] text-white',
    heroImg:'rounded-xl shadow-[0_0_50px_rgba(34,211,238,0.15)] border border-white/10',
    trustBadge:'bg-[#0a0f2c] border border-indigo-500/30 text-white shadow-[0_0_20px_rgba(99,102,241,0.2)] rounded-xl',
    trustIcon:'bg-indigo-900/50 text-cyan-400 rounded-full',trustText:'text-indigo-300',
    featCard:'rounded-2xl',featIcon:'bg-indigo-900/40 border border-indigo-500/20 text-cyan-400 rounded-xl',
    reviewCard:'rounded-2xl',reviewText:'text-indigo-100',reviewAvatar:'bg-indigo-900/80 text-cyan-400 rounded-full',
    inputStyle:'border-white/10 bg-[#0A0F2C] text-white focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 rounded-xl',
    footer:'bg-[#030014] text-indigo-400 border-t border-white/5',
  },
  soft_beauty: {
    bg:'bg-rose-50/30',textMain:'text-stone-800',textSec:'text-stone-500',font:'font-sans',
    promo:'bg-rose-200 text-rose-800 font-medium tracking-wide text-sm',header:'bg-white/70 backdrop-blur-xl border-b border-rose-100',
    brand:'text-rose-900 font-serif italic text-3xl',
    btnSecondary:'bg-rose-100 hover:bg-rose-200 text-rose-800 font-medium rounded-full px-6 py-2.5',
    btnPrimary:'bg-gradient-to-r from-rose-400 to-pink-500 hover:from-rose-500 hover:to-pink-600 text-white font-medium rounded-full px-10 py-4 shadow-xl shadow-rose-200/50',
    heroBg:'bg-gradient-to-b from-rose-100/50 to-transparent',
    accentBg:'bg-white text-rose-500 border border-rose-100 shadow-sm rounded-full',accentText:'text-rose-500 font-serif italic',
    heroBlob:'bg-gradient-to-tr from-rose-300 to-pink-200 opacity-20 filter blur-[80px]',
    sectionDark:'bg-stone-900 text-stone-100',sectionDarkAccent:'from-stone-800 to-stone-900 border-stone-700',sectionWhite:'bg-white',sectionLight:'bg-rose-50/50',
    card:'bg-white border border-rose-50 hover:border-rose-100 rounded-3xl shadow-sm hover:shadow-xl hover:shadow-rose-100/40 transition-all',
    checkoutBg:'bg-gradient-to-b from-rose-50/50 to-rose-100/30',
    checkoutCard:'border border-rose-100 bg-white shadow-2xl shadow-rose-200/40 rounded-[2rem]',checkoutDark:'bg-rose-900 text-rose-50',
    heroImg:'rounded-[2rem] shadow-2xl border-4 border-white',trustBadge:'bg-white border-rose-50 text-stone-800 shadow-rose-100/50 rounded-2xl',
    trustIcon:'bg-rose-50 text-rose-500 rounded-full',trustText:'text-stone-500',
    featCard:'rounded-3xl',featIcon:'bg-rose-50 text-rose-500 rounded-2xl',
    reviewCard:'rounded-3xl',reviewText:'text-stone-600',reviewAvatar:'bg-rose-100 text-rose-600 rounded-full',
    inputStyle:'border-rose-100 bg-rose-50/50 text-stone-800 focus:border-rose-400 rounded-xl',
    footer:'bg-rose-50 text-stone-500 border-t border-rose-100',
  },
  viral_tiktok: {
    bg:'bg-white',textMain:'text-black',textSec:'text-gray-800',font:'font-sans',
    promo:'bg-black text-yellow-400 font-black uppercase tracking-widest border-b-4 border-black text-lg',header:'bg-yellow-400 border-b-4 border-black',
    brand:'text-black font-black uppercase text-3xl',
    btnSecondary:'bg-black text-white border-2 border-black hover:bg-gray-900',
    btnPrimary:'bg-green-400 hover:bg-green-500 text-black border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-y-1 font-black uppercase',
    heroBg:'bg-blue-50',accentBg:'bg-yellow-400 text-black border-2 border-black font-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]',
    accentText:'text-red-500 font-black underline decoration-4 underline-offset-4 decoration-yellow-400',heroBlob:'hidden',
    sectionDark:'bg-yellow-400 text-black border-y-4 border-black',sectionDarkAccent:'from-black to-gray-900 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] text-white',
    sectionWhite:'bg-white border-y-4 border-black',sectionLight:'bg-rose-50 border-y-4 border-black',
    card:'bg-white border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-1 hover:shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] rounded-none',
    checkoutBg:'bg-purple-50',checkoutCard:'border-4 border-black shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] bg-white rounded-none',checkoutDark:'bg-yellow-400 text-black border-l-4 border-black',
    heroImg:'rounded-none border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]',
    trustBadge:'bg-white border-4 border-black text-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-none',trustIcon:'bg-yellow-400 border-2 border-black text-black rounded-full',trustText:'text-gray-800',
    featCard:'rounded-none',featIcon:'bg-yellow-400 border-2 border-black text-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] rounded-none',
    reviewCard:'rounded-none',reviewText:'text-black font-bold',reviewAvatar:'bg-black text-white rounded-full',
    inputStyle:'border-black bg-white text-black focus:border-black focus:ring-4 focus:ring-yellow-400 rounded-none shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
    footer:'bg-white text-black border-t-4 border-black',
  },
  organic_nature: {
    bg:'bg-[#FAFAFA]',textMain:'text-[#2C3E35]',textSec:'text-[#5C7162]',font:'font-sans',
    promo:'bg-[#3A5A40] text-[#E9EDC9] font-medium tracking-wide',header:'bg-white/80 backdrop-blur-md border-b border-[#E9EDC9]',
    brand:'text-[#3A5A40] font-serif text-2xl',
    btnSecondary:'bg-[#F2EDD7] hover:bg-[#E9EDC9] text-[#3A5A40] font-medium rounded-full px-6 py-2.5',
    btnPrimary:'bg-[#588157] hover:bg-[#3A5A40] text-white font-medium rounded-full px-10 py-4 shadow-lg shadow-[#588157]/30',
    heroBg:'bg-gradient-to-b from-[#E9EDC9]/30 to-transparent',
    accentBg:'bg-[#E9EDC9]/50 text-[#3A5A40] border border-[#CCD5AE] font-medium rounded-full',accentText:'text-[#588157] font-serif',
    heroBlob:'bg-gradient-to-tr from-[#CCD5AE] to-[#E9EDC9] opacity-30 filter blur-[90px]',
    sectionDark:'bg-[#2E3C33] text-[#E9EDC9]',sectionDarkAccent:'from-[#3A5A40] to-[#2E3C33] border-[#588157]/50',sectionWhite:'bg-white',sectionLight:'bg-[#F9F9F4]',
    card:'bg-white border border-[#E9EDC9] hover:border-[#CCD5AE] rounded-3xl shadow-sm hover:shadow-lg',
    checkoutBg:'bg-gradient-to-b from-[#F9F9F4] to-[#E9EDC9]/20',
    checkoutCard:'border border-[#CCD5AE] bg-white shadow-xl shadow-[#588157]/10 rounded-3xl',checkoutDark:'bg-[#3A5A40] text-[#E9EDC9]',
    heroImg:'rounded-[2rem] shadow-xl border-4 border-[#E9EDC9]',trustBadge:'bg-white border-[#E9EDC9] text-[#2C3E35] shadow-lg rounded-2xl',
    trustIcon:'bg-[#E9EDC9] text-[#588157] rounded-full',trustText:'text-[#5C7162]',
    featCard:'rounded-3xl',featIcon:'bg-[#E9EDC9]/50 text-[#588157] rounded-2xl',
    reviewCard:'rounded-3xl',reviewText:'text-[#2C3E35]',reviewAvatar:'bg-[#E9EDC9] text-[#3A5A40] rounded-full',
    inputStyle:'border-[#E9EDC9] bg-[#FAFAFA] text-[#2C3E35] focus:border-[#588157] rounded-xl',
    footer:'bg-[#FAFAFA] text-[#5C7162] border-t border-[#E9EDC9]',
  },
  bold_sales: {
    bg:'bg-gray-100',textMain:'text-black',textSec:'text-gray-700',font:'font-sans',
    promo:'bg-red-600 text-white font-black uppercase text-xl py-3 border-b-4 border-red-800',header:'bg-white border-b-2 border-gray-200 shadow-sm',
    brand:'text-red-600 font-black uppercase text-3xl italic tracking-tighter',
    btnSecondary:'bg-gray-200 hover:bg-gray-300 text-black font-bold uppercase rounded-sm px-6 py-2',
    btnPrimary:'bg-[#FFDE00] hover:bg-[#E6C800] text-black font-black uppercase rounded-sm px-10 py-5 text-2xl shadow-[0_5px_0_0_#CCB100] hover:shadow-[0_2px_0_0_#CCB100] hover:translate-y-[3px] transition-all',
    heroBg:'bg-white',accentBg:'bg-red-100 text-red-600 border-2 border-red-600 font-black uppercase rounded-sm',accentText:'text-red-600 font-black bg-red-100 px-2',heroBlob:'hidden',
    sectionDark:'bg-black text-white border-y-4 border-red-600',sectionDarkAccent:'from-gray-900 to-black border-2 border-red-600 shadow-2xl',sectionWhite:'bg-white',sectionLight:'bg-gray-100 border-y border-gray-200',
    card:'bg-white border-2 border-gray-200 hover:border-red-600 rounded-sm shadow-md hover:shadow-xl hover:-translate-y-1',
    checkoutBg:'bg-gray-200',checkoutCard:'border-0 bg-white shadow-2xl rounded-sm ring-4 ring-black/5',checkoutDark:'bg-gray-900 text-white border-l-4 border-red-600',
    heroImg:'rounded-sm shadow-xl border-4 border-gray-200',trustBadge:'bg-white border-2 border-gray-200 text-black shadow-xl rounded-sm',
    trustIcon:'bg-yellow-400 text-black rounded-full',trustText:'text-gray-600 font-bold',
    featCard:'rounded-sm',featIcon:'bg-red-100 text-red-600 rounded-lg',
    reviewCard:'rounded-sm',reviewText:'text-gray-800 font-bold',reviewAvatar:'bg-gray-200 text-black rounded-lg',
    inputStyle:'border-gray-300 bg-gray-50 text-black focus:border-red-600 rounded-sm font-bold',
    footer:'bg-black text-gray-500 border-t-4 border-red-600',
  },
};

export const layoutTokens: Record<AITemplateName, Record<string,string>> = {
  minimal_luxury: {
    heroWrap:'flex items-center gap-12',heroText:'flex-1',heroImg:'flex-1',
    featGrid:'grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8',
    reviewsWrap:'flex gap-6 overflow-x-auto pb-4 snap-x',reviewCard:'min-w-[280px] snap-center p-8',
    checkoutWrap:'flex flex-col md:flex-row',checkoutLeft:'md:w-5/12',checkoutRight:'md:w-7/12 p-8 md:p-10',
  },
  dark_futuristic: {
    heroWrap:'flex items-center gap-12 flex-row-reverse',heroText:'flex-1',heroImg:'flex-1',
    featGrid:'grid-cols-1 sm:grid-cols-2 gap-6 max-w-4xl mx-auto',
    reviewsWrap:'grid grid-cols-1 md:grid-cols-3 gap-6',reviewCard:'p-6 md:p-8',
    checkoutWrap:'flex flex-col md:flex-row',checkoutLeft:'md:w-1/2',checkoutRight:'md:w-1/2 p-6 md:p-12',
  },
  soft_beauty: {
    heroWrap:'flex flex-col items-center gap-10 text-center',heroText:'w-full flex flex-col items-center',heroImg:'w-full max-w-2xl mx-auto',
    featGrid:'grid-cols-1 sm:grid-cols-3 gap-8 max-w-6xl mx-auto',
    reviewsWrap:'flex gap-8 overflow-x-auto pb-4 snap-x',reviewCard:'min-w-[280px] snap-center p-10',
    checkoutWrap:'flex flex-col md:flex-row-reverse',checkoutLeft:'md:w-5/12',checkoutRight:'md:w-7/12 p-8 md:p-10',
  },
  viral_tiktok: {
    heroWrap:'flex flex-col items-center gap-8 text-center',heroText:'w-full flex flex-col items-center',heroImg:'w-full max-w-md mx-auto',
    featGrid:'grid-cols-1 max-w-xl mx-auto gap-6',
    reviewsWrap:'grid grid-cols-1 max-w-xl mx-auto gap-6',reviewCard:'p-6 text-center',
    checkoutWrap:'flex flex-col max-w-xl mx-auto',checkoutLeft:'w-full',checkoutRight:'w-full p-6 sm:p-10',
  },
  organic_nature: {
    heroWrap:'flex items-center gap-16',heroText:'w-7/12',heroImg:'w-5/12',
    featGrid:'grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-12 max-w-6xl mx-auto',
    reviewsWrap:'grid grid-cols-1 md:grid-cols-3 gap-8',reviewCard:'p-8',
    checkoutWrap:'flex flex-col md:flex-row',checkoutLeft:'md:w-1/2',checkoutRight:'md:w-1/2 p-8 md:p-10',
  },
  bold_sales: {
    heroWrap:'flex flex-col items-center gap-10 text-center',heroText:'w-full flex flex-col items-center',heroImg:'w-full max-w-3xl mx-auto',
    featGrid:'grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 max-w-7xl mx-auto',
    reviewsWrap:'grid grid-cols-1 sm:grid-cols-3 gap-4',reviewCard:'p-6 text-center',
    checkoutWrap:'flex flex-col max-w-3xl mx-auto',checkoutLeft:'w-full',checkoutRight:'w-full p-6 sm:p-10',
  },
};
